### ISSUE TITLE
Will this allow working with openCV on MS HoloLens?

### ISSUE THREAD

**Issue by eladar** [cvwin/cvwin#1]
Hi @harrywye, I'm looking for an openCV package that works with the HoloLens (C#,UWP), have you tried integrating your wrapper with an HoloLens app?

Thanks,
-e

**Comment by harrywye** [comment]
Hi @eladar, the answer is yes and no.

"OpenCV.Win" nuget packages (not native versions) are not wrappers. They are special native C++ build that will work with UWP apps on Windows 10. There are a number of ways you can use these packages for HoloLens C# apps. (I haven't had a chance to really test all these scenarios yet.)

(1) Create a Windows Runtime Component library in C++, which includes OpenCV functionalities (using the OpenCV.Win packages). Link this library in a UWP C# app. 
(2) Drop in the library in the plugin folder (e.g., wsa) in a Unity HoloLens app.
(3) Create a C# wrapper library which includes the APIs you will need.

These packages are directly useable in UWP C++ apps (including HoloLens apps), but not in C# apps. (3) might be a bit too complicated, but (1) and (2) are not that difficult if you have some background in C++/CX.

**Comment by enghch** [comment]
That's a great explanation. It feels like it should be on the home .md page. One question, if we opt for option #1 where to we get the correct .h files. I assume we'll need to include several opencv header files in order to write code against these binaries.

**Comment by harrywye** [comment]
@enghch, in your C++ windows runtime component library, install the necessary nuget packages (e.g., OpenCV.Win.Core, OpenCV.Win.ImgProc, etc.). Then, you don't have to worry about where the header files are coming from (assuming that you are using Visual Studio for dev). Nuget takes care of header include dirs, lib dirs, and dlls, etc. You can include the OpenCV header files using `<>` in your h/cpp files like this:

    #include <opencv2/core.hpp>
    #include <opencv2/imgproc.hpp>
    ... 

HTH.

**Comment by enghch** [comment]
Wow! That's glorious! I had no idea nuget could set up all the header and libs like that. Thank you very much! I'm excited to create my own Windows Runtime Component so I can (finally) easily access OpenCV from C# but I'm even more excited to see what you come up with. :)
