### ISSUE TITLE
imshow is not working

### ISSUE THREAD

**Issue by nicolasayotte** [cvwin/cvwin#4]
When I include a call to cv::imshow in either debug or release modes, the program does not run (though it compiles) anymore claiming to require the zlibd1.dll (in debug) library. This seems to be a slight oversight in the packaging where the zlib third party should be included. It also fails in release for a similar reason.

I am using Windows 10 64-bit. The rest of the library is working fine except the functions from that particular library with imshow, imsave, etc.

**Comment by harrywye** [comment]
@nicolasayotte This is a known issue. I swear I added relevant info in the release note somewhere, but I cannot find it at this point. 

You will need to install zdlib separately. (If I remember correctly, you can just copy a binary into a folder in your system path (like "system32"). You can easily find a pre-built zdlib on the web.) cvwin is merely a build of an OpenCV distribution on Windows, and if you feel like zdlib dependency should have been added, OpenCV is the right place to address that issue.

Please let me know if you are still having an issue.

**Comment by nicolasayotte** [comment]
@harrywye I absolutely agree that a third party could be left out and have tried installing a nuget for zlib. However, the dll for this third party is never "zlibd1.dll" which had me thinking that you had perhaps changed the reference in the source code prior to building it as "zlibd1.dll" is nowhere in the opencv source code as it stands on GitHub. I might be wrong I am no CMake expert. :)

**Comment by harrywye** [comment]
@nicolasayotte Although it's been a while, I can assure you that I did not mess with CMake files. (I'm no CMake expert either. ;)). I do remember though, after installing a zlib binary from a external place (a sourceforge download page?), my test app worked just fine. Did I have to change the zlib dll name? Cannot remember. Unfortunately, I cannot even verify it at this point (without having to set up a new dev environment). But, it should be a simple fix once you know what to look for.

**Comment by harrywye** [comment]
@nicolasayotte BTW, just to be sure, "d" in zlibd stands for debug. (If you cannot find a debug version of pre-built zlib, you might have to build it. Cannot recall exactly what I did.) I quickly tried to google it but couldn't find the "official" zlib site, which I used last time. (So many spam sites.) The site I used, if I remember correctly, was like 10~20 years old.

**Comment by nicolasayotte** [comment]
@harrywye I know, this is why the zlibd1.dll bugs me (the "1" looks out of place) and the zlib nuget includes a zlibd.dll without the 1. I will try to rename a pre-built package or to build it and rename it

**Comment by harrywye** [comment]
@nicolasayotte One thing I can tell you for sure (with 97% confidence :)) is that I actually downloaded a prebuilt binary from somewhere rather than using a nuget package. I'm not sure if it will make a difference though.

**Comment by nicolasayotte** [comment]
@harrywye Using the zlib official nuget and renaming the debug (x64 and x86) libraries zlibd1.dll, zlibd1.pdf, zlibd1.lib in all the nuget information files solved it. :)
Thank you for helping distribute opencv to Windows. 👍

**Comment by harrywye** [comment]
Glad to hear that. Thanks for sharing the info! Good luck with your project.
